controller_manager:
  ros__parameters:
    update_rate: 1000

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_contoller:
  ros__parameters:
    command_interfaces:
      -position
    state_interfaces:
      -position
      -velocity
    joints:
      -Revolute 36
      -Revolute 38
      -Revolute 41
      -Revolute 48